# Generated by Django 5.1.3 on 2024-11-12 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('postalCode', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('jobType', models.CharField(blank=True, choices=[('Remote', 'Remote'), ('Hybrid', 'Hybrid'), ('Office', 'Office')], max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hourly', models.CharField(blank=True, max_length=4, null=True)),
                ('monthly', models.CharField(blank=True, max_length=7, null=True)),
                ('yearly', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('experience', models.CharField(choices=[('Intern', 'Intern'), ('Junior', 'Junior'), ('Regular', 'Regular'), ('Senior', 'Senior'), ('Staff', 'Staff')], max_length=30)),
                ('timeDimension', models.CharField(choices=[('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time')], max_length=30)),
                ('isPremium', models.BooleanField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('changedAt', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
                ('location', models.ManyToManyField(to='api.location')),
                ('salary', models.ManyToManyField(blank=True, to='api.salary')),
            ],
        ),
    ]
