# Generated by Django 5.1.3 on 2024-11-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_location_salary_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='location',
        ),
        migrations.RemoveField(
            model_name='job',
            name='salary',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Salary',
        ),
        migrations.AddField(
            model_name='job',
            name='salary',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
