# Generated by Django 5.1.3 on 2024-11-12 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_job_location_remove_job_salary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('postalCode', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('jobType', models.CharField(blank=True, choices=[('Remote', 'Remote'), ('Hybrid', 'Hybrid'), ('Office', 'Office')], max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hourly', models.CharField(blank=True, max_length=4, null=True)),
                ('monthly', models.CharField(blank=True, max_length=7, null=True)),
                ('yearly', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='job',
            name='location',
        ),
        migrations.RemoveField(
            model_name='job',
            name='salary',
        ),
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.ManyToManyField(to='api.location'),
        ),
        migrations.AddField(
            model_name='job',
            name='salary',
            field=models.ManyToManyField(blank=True, to='api.salary'),
        ),
    ]
