# Generated by Django 5.1.3 on 2024-11-12 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_user_jobapplication_alter_user_jobofferposted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='hourly',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='salary',
            name='monthly',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='salary',
            name='yearly',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
