# Generated by Django 5.1.3 on 2024-11-14 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_user_jobapplication_alter_user_jobofferposted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
